Análise exploratória do CSV de classificação

1. Quantas imagens são “benign” e “malign” em real_class?

In [9]:
import pandas as pd

data = pd.read_csv('C:/Users/anacl/OneDrive/Documents/UFU/LIPAI/Semana06/classification_results_trial_0001.csv')
data

       image_path real_class predicted_class  prob_benign  prob_malign
0   image_001.jpg     malign          malign     0.031429     0.968571
1   image_002.jpg     benign          benign     0.636410     0.363590
2   image_003.jpg     malign          malign     0.314356     0.685644
3   image_004.jpg     benign          benign     0.508571     0.491429
4   image_005.jpg     benign          benign     0.907566     0.092434
..            ...        ...             ...          ...          ...
95  image_096.jpg     malign          malign     0.349210     0.650790
96  image_097.jpg     benign          benign     0.725956     0.274044
97  image_098.jpg     benign          benign     0.897110     0.102890
98  image_099.jpg     benign          benign     0.887086     0.112914
99  image_100.jpg     benign          benign     0.779876     0.220124

[100 rows x 5 columns]

In [4]:
data['real_class'].value_counts()

real_class
malign    55
benign    45
Name: count, dtype: int64


2. Identifique em quais imagens o modelo errou a predição.

In [15]:
falsos_positivos = data[(data['real_class'] == 'benign') & (data['predicted_class'] == 'malign')]
falsos_negativos = data[(data['real_class'] == 'malign') & (data['predicted_class'] == 'benign')]

In [16]:
falsos_positivos

       image_path real_class predicted_class  prob_benign  prob_malign
41  image_042.jpg     benign          malign     0.251782     0.748218
67  image_068.jpg     benign          malign     0.186519     0.813481
80  image_081.jpg     benign          malign     0.341066     0.658934

In [17]:
falsos_negativos

       image_path real_class predicted_class  prob_benign  prob_malign
20  image_021.jpg     malign          benign     0.807440     0.192560
26  image_027.jpg     malign          benign     0.818015     0.181985
27  image_028.jpg     malign          benign     0.860731     0.139269
46  image_047.jpg     malign          benign     0.609564     0.390436
65  image_066.jpg     malign          benign     0.835302     0.164698
69  image_070.jpg     malign          benign     0.590893     0.409107
70  image_071.jpg     malign          benign     0.677564     0.322436
76  image_077.jpg     malign          benign     0.690938     0.309062
91  image_092.jpg     malign          benign     0.897216     0.102784

3. Verifique se o modelo estava confiante mesmo quando errou.

In [ ]:
erros = data[data['real_class'] != data['predicted_class']]

In [19]:
erros

       image_path real_class predicted_class  prob_benign  prob_malign
20  image_021.jpg     malign          benign     0.807440     0.192560
26  image_027.jpg     malign          benign     0.818015     0.181985
27  image_028.jpg     malign          benign     0.860731     0.139269
41  image_042.jpg     benign          malign     0.251782     0.748218
46  image_047.jpg     malign          benign     0.609564     0.390436
65  image_066.jpg     malign          benign     0.835302     0.164698
67  image_068.jpg     benign          malign     0.186519     0.813481
69  image_070.jpg     malign          benign     0.590893     0.409107
70  image_071.jpg     malign          benign     0.677564     0.322436
76  image_077.jpg     malign          benign     0.690938     0.309062
80  image_081.jpg     benign          malign     0.341066     0.658934
91  image_092.jpg     malign          benign     0.897216     0.102784

In [ ]:
resumo_erros = erros.groupby(['real_class', 'predicted_class']).size()
print("Distribuição dos tipos de erro:")
print(resumo_erros)

Distribuição dos tipos de erro:
real_class  predicted_class
benign      malign             3
malign      benign             9
dtype: int64

4. Calcule: 

a. TP (real malign, previsto malign)

In [29]:
tp_malign = data[(data['real_class'] == 'malign') & (data['predicted_class'] == 'malign')]

In [31]:
quantidade_tp = len(tp_malign)
quantidade_tp

46

b. TN (real benign, previsto benign)

In [ ]:
tn_benign = data[(data['real_class'] == 'benign') & (data['predicted_class'] == 'benign')]

In [34]:

quantidade_tn = len(tn_benign)
quantidade_tn

42

c. FP (real benign, previsto malign)

In [38]:
fp_benign = data[(data['real_class'] == 'benign') & (data['predicted_class'] == 'malign')]

In [39]:
quantidade_fp = len(fp_benign)
quantidade_fp

3

d. FN (real malign, previsto benign)

In [42]:
fp_malign = data[(data['real_class'] == 'malign') & (data['predicted_class'] == 'benign')]

In [43]:
quantidade_fn = len(fp_malign)
quantidade_fn

9

5. Calcule: 

a. Acurácia: (TP+TN)/(TP+TN+FP+FN)

In [46]:
total = quantidade_tp + quantidade_tn + quantidade_fp + quantidade_fn
acuracia = (quantidade_tp + quantidade_tn) / total if total > 0 else 0
acuracia

0.88

b. Precisão: TP/(TP+FP)

In [48]:
precisao = quantidade_tp / (quantidade_tp + quantidade_fp)
precisao

0.9387755102040817

c. Recall: TP/(TP+FN)

In [50]:
recall = quantidade_tp / (quantidade_tp + quantidade_fn)
recall

0.8363636363636363

d. Especificidade: TN/(TN+FP)

In [51]:
especificidade = quantidade_tn / (quantidade_tn + quantidade_fp)
especificidade

0.9333333333333333

6. Encontre as 5 imagens benign com menor prob_benign. O que isso pode indicar?

In [52]:
benignos = data[data['real_class'] == 'benign']

menores_confiancas = benignos.sort_values(by='prob_benign', ascending=True).head(5)
menores_confiancas

       image_path real_class predicted_class  prob_benign  prob_malign
67  image_068.jpg     benign          malign     0.186519     0.813481
41  image_042.jpg     benign          malign     0.251782     0.748218
80  image_081.jpg     benign          malign     0.341066     0.658934
47  image_048.jpg     benign          benign     0.502679     0.497321
3   image_004.jpg     benign          benign     0.508571     0.491429

O modelo comete erros de classificação apresentando alta confiança. Isso sugere que existem padrões visuais nas lesões benignas que ele está aprendendo como se fossem características de malignidade.

7. Encontre as 5 imagens malign com maior prob_benign. O que isso pode indicar?

In [54]:
benignos = data[data['real_class'] == 'benign']

maiores_confiancas = benignos.sort_values(by='prob_benign', ascending=False).head(5)
maiores_confiancas

       image_path real_class predicted_class  prob_benign  prob_malign
54  image_055.jpg     benign          benign     0.985650     0.014350
39  image_040.jpg     benign          benign     0.971782     0.028218
40  image_041.jpg     benign          benign     0.962447     0.037553
34  image_035.jpg     benign          benign     0.942910     0.057090
78  image_079.jpg     benign          benign     0.936730     0.063270

O modelo está classificando lesões que são clinicamente malignas como benignas. Este é um tipo de erro que deve ser minimizado , pois pode levar à falta de tratamento ou atraso no diagnóstico. As imagens malignas com alta prob_benign podem apresentar características visuais muito discretas, que não são facilmente capturadas pelo extrator de características do modelo.